// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfVkUGjdfX6-Iv_DryLR8OXVGrhjJWSjs',
    appId: '1:968963139908:web:5ad3ec01d0b9e9b67f0f11',
    messagingSenderId: '968963139908',
    projectId: 'atelier4-z-elkhalfaoui-iir5g2',
    authDomain: 'atelier4-z-elkhalfaoui-iir5g2.firebaseapp.com',
    storageBucket: 'atelier4-z-elkhalfaoui-iir5g2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf0B5pDZoteqVRGTmHwZDCQxTPloxV6gQ',
    appId: '1:968963139908:android:0525e84ca425f7e47f0f11',
    messagingSenderId: '968963139908',
    projectId: 'atelier4-z-elkhalfaoui-iir5g2',
    storageBucket: 'atelier4-z-elkhalfaoui-iir5g2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYV6x8cnpp7gHWcLd2jMXSkobU0jGuwJU',
    appId: '1:968963139908:ios:67238fa798b13ac87f0f11',
    messagingSenderId: '968963139908',
    projectId: 'atelier4-z-elkhalfaoui-iir5g2',
    storageBucket: 'atelier4-z-elkhalfaoui-iir5g2.appspot.com',
    iosBundleId: 'com.example.atelier4ZElkhalfaouiIir5g2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYV6x8cnpp7gHWcLd2jMXSkobU0jGuwJU',
    appId: '1:968963139908:ios:08d90d972ae4f60c7f0f11',
    messagingSenderId: '968963139908',
    projectId: 'atelier4-z-elkhalfaoui-iir5g2',
    storageBucket: 'atelier4-z-elkhalfaoui-iir5g2.appspot.com',
    iosBundleId: 'com.example.atelier4ZElkhalfaouiIir5g2.RunnerTests',
  );
}
